version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint webapp with Flake8 and black
          command: flake8 canonicalwebteam tests && black --line-length 79 --check canonicalwebteam tests
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -yy python3-venv
            pip3 install poetry==0.12.11 # https://github.com/sdispater/poetry/issues/1060 can probably be unpinned when you read this.
            poetry install
      - run:
          name: Print env
          command: env
      - run:
          name: Run Python tests
          command: poetry run pytest

workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python

